@extends('layouts.app') @section('title','Темы практикума') @section('content')
<div class="d-flex justify-content-between mb-3"><div><h1>Темы практикума</h1><a href="{{ route('admin.index') }}">← Админка</a></div><button class="btn btn-primary" onclick="editTopic()">Добавить тему</button></div>
<div id="alert"></div>
<div class="alert alert-info"><strong>HTML-практикумы:</strong> можно загрузить отдельный <code>.html</code>/<code>.htm</code> файл. Он хранится вне <code>public</code> и открывается только авторизованному пользователю по адресу <code>/practice/slug</code>. В HTML доступны <code>window.PRACTICE_API</code> и шаблоны <code>@{{PRACTICE_SESSION_URL}}</code>, <code>@{{PRACTICE_RESULT_URL}}</code>.</div>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Порядок</th><th>Модуль</th><th>Название</th><th>URL</th><th>HTML</th><th>Статус</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div>
<div class="modal fade" id="modal"><div class="modal-dialog modal-xl"><form class="modal-content" id="form" enctype="multipart/form-data"><div class="modal-header"><h5 class="modal-title">Тема</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="id"><div class="row g-3">
<div class="col-md-8"><label class="form-label">Название</label><input id="title" class="form-control" required></div><div class="col-md-4"><label class="form-label">Порядок</label><input id="sort_order" type="number" min="0" class="form-control" value="0"></div>
<div class="col-md-6"><label class="form-label">Модуль/раздел</label><input id="module" class="form-control" required></div><div class="col-md-6"><label class="form-label">Slug URL</label><input id="slug" class="form-control" placeholder="создастся автоматически"></div>
<div class="col-12"><label class="form-label">Краткое описание</label><textarea id="excerpt" class="form-control" rows="2"></textarea></div>
<div class="col-12"><div class="card border-primary-subtle"><div class="card-body"><label class="form-label fw-semibold">Интерактивный HTML-практикум</label><input id="html_file" type="file" class="form-control" accept=".html,.htm,text/html"><div class="form-text">Максимум 3 МБ. Загруженный файл заменит предыдущий.</div><div id="htmlCurrent" class="mt-2 small"></div><div class="form-check mt-2 d-none" id="removeHtmlWrap"><input id="remove_html" class="form-check-input" type="checkbox"><label class="form-check-label" for="remove_html">Удалить текущий HTML-файл</label></div></div></div></div>
<div class="col-12"><label class="form-label">Обычное содержание страницы (HTML, необязательно)</label><textarea id="content" class="form-control font-monospace" rows="10"></textarea><div class="form-text">Используется для обычной страницы <code>/topics/slug</code>. Для интерактивного практикума можно оставить пустым.</div></div>
<div class="col-12"><div class="form-check"><input id="published" class="form-check-input" type="checkbox"><label class="form-check-label">Опубликована</label></div></div>
</div></div><div class="modal-footer"><button class="btn btn-primary">Сохранить</button></div></form></div></div>
@endsection @push('scripts')<script src="/js/admin-topics.js"></script>@endpush
